# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ck8ictjy0-capi-aws
  namespace: ck8ictjy0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ck8ictjy0-capi-aws
subjects:
- kind: ServiceAccount
  name: ck8ictjy0-capi-aws
